version: '3.8'

services:
  postgres:
    image: postgres:18.1-bookworm
    container_name: perfect-api-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: perfect-api-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres
    restart: always

  redis:
    image: redis:7-alpine
    container_name: perfect-api-redis
    ports:
      - "6379:6379"
    restart: always

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI dashboard port
    restart: always


volumes:
  postgres_data:
